name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  verify:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea # v4.2.1
        with:
          cache: true
          github_token: ${{ github.token }}
          install: true
          version: 2026.8.3
      - run: mise run check

  release:
    needs: verify
    runs-on: ubuntu-24.04
    permissions:
      attestations: write
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: cli/gh-extension-precompile@76961aa3bd1123d0a6fd42d0a41aca0696937c39 # v2.2.0
        with:
          build_script_override: .mise/tasks/release/build
          generate_attestations: true
          go_version_file: go.mod
